'use client';
import { FormEvent, useState } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { api } from '@/lib/api';
import { Card, PageHeader } from '@/components/ui/core';
import { downloadPortal, PortalReportView, type PortalSnapshot } from '@/components/portal-report';

type Summary={brandName:string;reports:{id:string;year:number;month:number;version:number;publishedAt:string}[];documents:{id:string;fileName:string;sharedAt:string}[];questions:{id:string;reportId:string;question:string;answer:string;createdAt:string}[]};
const button='rounded-lg border px-3 py-2 text-sm disabled:opacity-50';
export default function Page(){
  const qc=useQueryClient();const[reportId,setReportId]=useState('');const[error,setError]=useState('');const[busy,setBusy]=useState(false);const[notice,setNotice]=useState('');
  const summary=useQuery({queryKey:['portal'],queryFn:()=>api<Summary>('/api/portal'),refetchInterval:30000});
  const report=useQuery({queryKey:['portal-report',reportId],queryFn:()=>api<PortalSnapshot>('/api/portal/reports/'+reportId),enabled:!!reportId,refetchInterval:30000});
  const visible=!!summary.data?.reports.some(r=>r.id===reportId);
  async function ask(e:FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;const form=e.currentTarget;setBusy(true);setError('');setNotice('');try{await api('/api/portal/questions',{method:'POST',body:JSON.stringify({reportId,question:new FormData(form).get('question')})});form.reset();setNotice('Sorunuz OVO ekibine iletildi. Yanıtı bu sayfada görebilirsiniz.');await qc.invalidateQueries({queryKey:['portal']});}catch(e){setError(e instanceof Error?e.message:'Soru gönderilemedi.');}finally{setBusy(false);}}
  async function download(path:string,name:string){setError('');try{await downloadPortal(path,name);}catch(e){setError(e instanceof Error?e.message:'Dosya indirilemedi.');}}
  if(summary.isPending)return <p role="status">Paylaşımlarınız yükleniyor…</p>;
  if(summary.isError)return <p role="alert">Paylaşımlar alınamadı. {summary.error.message}</p>;
  const data=summary.data;
  return <><div className="print:hidden"><PageHeader title={data.brandName+' · Marka portalı'} description="Yalnız size açılan raporları ve belgeleri görürsünüz. Bu alan anlaşma kabul etme, ödeme veya dönem onaylama ekranı değildir."/><Card className="space-y-3 p-5"><h2 className="font-semibold">Nasıl kullanılır?</h2><p className="text-sm">Bir rapor sürümü seçin, rakamları inceleyin; isterseniz tabloyu indirin veya PDF olarak kaydedin. Anlaşılmayan bir tutar varsa raporun altından soru gönderin. Belge indirirken dosya adını kontrol edin. Paylaşım geri çekilirse erişim kapanır; daha önce indirdiğiniz dosya cihazınızdan silinmez.</p><label className="block text-sm">Yayımlanmış rapor<select className="input mt-2" value={reportId} onChange={e=>{setReportId(e.target.value);setError('');setNotice('');}}><option value="">Rapor seçin</option>{data.reports.map(r=><option key={r.id} value={r.id}>{r.month}/{r.year} · Sürüm {r.version}</option>)}</select></label>{!data.reports.length&&<p className="text-sm">Henüz yayımlanmış rapor yok. OVO ekibi paylaştığında burada görünecek.</p>}</Card></div>
  {error&&<p role="alert" className="my-3 text-red-700">{error}</p>}{notice&&<p role="status" className="my-3">{notice}</p>}
  {reportId&&(!visible?<p role="alert">Bu rapor artık paylaşılmıyor. Başka bir sürüm seçin.</p>:report.isPending?<p role="status">Rapor yükleniyor…</p>:report.isError?<p role="alert">Rapor açılamadı; paylaşım geri çekilmiş olabilir.</p>:report.data&&<><PortalReportView data={report.data}/><div className="my-3 flex flex-wrap gap-3 print:hidden"><button className={button} onClick={()=>void download(`/api/portal/reports/${reportId}/csv`,`rapor-v${report.data!.version}.csv`)}>Tabloyu indir</button><button className={button} onClick={()=>window.print()}>Yazdır / PDF kaydet</button></div><form className="my-4 space-y-3 print:hidden" onSubmit={ask}><label className="block text-sm">Bu raporla ilgili sorunuz<textarea required maxLength={2000} name="question" className="input mt-2" rows={3} disabled={busy}/></label><button disabled={busy} className={button}>{busy?'Gönderiliyor…':'Açıklama iste'}</button></form></>)}
  <div className="space-y-4 print:hidden"><Card className="p-5"><h2 className="font-semibold">Paylaşılan belgeler</h2>{data.documents.length?data.documents.map(d=><button className="mt-3 block max-w-full break-all text-left text-sm underline" key={d.id} onClick={()=>void download(`/api/portal/documents/${d.id}/download`,d.fileName)}>{d.fileName}</button>):<p className="mt-3 text-sm">Henüz belge paylaşılmadı.</p>}</Card><Card className="p-5"><h2 className="font-semibold">Sorularım ve yanıtlar</h2><p className="mt-2 text-sm">Yalnız bu hesapla gönderdiğiniz sorular gösterilir. E-posta bildirimi gönderilmez; yanıtlar burada görünür.</p>{data.questions.map(q=><div className="mt-3 rounded-lg border p-3 text-sm" key={q.id}><p className="whitespace-pre-wrap break-words font-semibold">{q.question}</p><p className="mt-2 whitespace-pre-wrap break-words">{q.answer||'OVO ekibinin yanıtı bekleniyor.'}</p></div>)}{!data.questions.length&&<p className="mt-3 text-sm">Henüz soru göndermediniz.</p>}</Card></div></>;
}
