'use client';
import { useEffect } from 'react';
import { useQuery } from '@tanstack/react-query';
import { api, token, logout, type SessionUser } from '@/lib/api';
import type { ReactNode } from 'react';
import { BookOpen, CheckCircle2, Clock3, Lightbulb } from 'lucide-react';

function slug(value:string){return value.toLocaleLowerCase('tr-TR').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ı/g,'i').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}
function inline(value:string){return value.split(/(\*\*.*?\*\*|`.*?`)/g).filter(Boolean).map((part,i)=>part.startsWith('**')&&part.endsWith('**')?<strong key={i}>{part.slice(2,-2)}</strong>:part.startsWith('`')&&part.endsWith('`')?<code key={i} className="rounded bg-[#eef0f2] px-1.5 py-0.5 text-[.9em] text-[#303030]">{part.slice(1,-1)}</code>:part)}
function renderMarkdown(markdown:string){const lines=markdown.split('\n');const output:ReactNode[]=[];let i=0;while(i<lines.length){const line=lines[i].trim();if(!line||line==='---'){i++;continue}if(line.startsWith('# ')){i++;continue}const heading=line.match(/^(#{2,4})\s+(.+)$/);if(heading){const level=heading[1].length;const text=heading[2];const cls=level===2?'mt-12 border-t border-[#e3e5e7] pt-10 text-2xl font-bold tracking-tight':level===3?'mt-8 text-lg font-bold':'mt-6 font-bold';const Tag=(level===2?'h2':level===3?'h3':'h4') as 'h2'|'h3'|'h4';output.push(<Tag id={slug(text)} className={`${cls} scroll-mt-24`} key={`h-${i}`}>{inline(text)}</Tag>);i++;continue}if(/^[-*] \[[ xX]\] /.test(line)){const items:ReactNode[]=[];while(i<lines.length&&/^[-*] \[[ xX]\] /.test(lines[i].trim())){const current=lines[i].trim();const done=/^[-*] \[[xX]\]/.test(current);items.push(<li className="flex gap-3" key={i}><span className={`mt-1 grid h-5 w-5 shrink-0 place-items-center rounded border ${done?'border-[#008060] bg-[#008060] text-white':'border-[#b8babe] bg-white'}`}>{done?'✓':''}</span><span>{inline(current.replace(/^[-*] \[[ xX]\] /,''))}</span></li>);i++}output.push(<ul className="my-4 space-y-2" key={`check-${i}`}>{items}</ul>);continue}if(line.startsWith('- ')){const items:ReactNode[]=[];while(i<lines.length&&lines[i].trim().startsWith('- ')){items.push(<li key={i}>{inline(lines[i].trim().slice(2))}</li>);i++}output.push(<ul className="my-4 list-disc space-y-2 pl-6 text-[#4a4d50] marker:text-[#008060]" key={`ul-${i}`}>{items}</ul>);continue}if(/^\d+\. /.test(line)){const items:ReactNode[]=[];while(i<lines.length&&/^\d+\. /.test(lines[i].trim())){items.push(<li key={i}>{inline(lines[i].trim().replace(/^\d+\. /,''))}</li>);i++}output.push(<ol className="my-4 list-decimal space-y-2 pl-6 text-[#4a4d50] marker:font-bold marker:text-[#008060]" key={`ol-${i}`}>{items}</ol>);continue}const paragraph=[line];i++;while(i<lines.length&&lines[i].trim()&&!/^(#{1,4})\s|^[-*] |^\d+\. |^---$/.test(lines[i].trim())){paragraph.push(lines[i].trim());i++}output.push(<p className="my-4 text-[16px] leading-7 text-[#4a4d50]" key={`p-${i}`}>{inline(paragraph.join(' '))}</p>)}return output}

function GuideContent({markdown,updatedAt}:{markdown:string;updatedAt:string}){const updated=new Date(updatedAt);const headings=markdown.split('\n').filter(x=>x.startsWith('## ')).map(x=>x.slice(3));return <div className="mx-auto max-w-[1240px]"><section className="relative overflow-hidden rounded-2xl bg-[#111315] px-6 py-8 text-white shadow-sm sm:px-9"><div className="absolute -right-20 -top-24 h-64 w-64 rounded-full bg-[#00a47c]/20 blur-3xl"/><div className="relative max-w-3xl"><div className="mb-4 inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/5 px-3 py-1.5 text-sm text-[#b7f1df]"><BookOpen size={16}/> Ekip eğitim merkezi</div><h1 className="text-3xl font-bold tracking-tight sm:text-4xl">OVO Growth OS Kullanım Rehberi</h1><p className="mt-4 max-w-2xl text-base leading-7 text-[#c9ced1]">Marka kaydından değerlendirmeye, anlaşmadan aylık kapanışa kadar sistemi güvenli ve doğru kullanmak için ihtiyaç duyacağınız her şey.</p><div className="mt-5 flex flex-wrap gap-4 text-sm text-[#c9ced1]"><span className="flex items-center gap-2"><Clock3 size={15}/> Son güncelleme: {new Intl.DateTimeFormat('tr-TR',{dateStyle:'long',timeStyle:'short',timeZone:'Europe/Istanbul'}).format(updated)}</span><span className="flex items-center gap-2"><CheckCircle2 size={15}/> Uygulamanın güncel sürümüyle uyumlu</span></div></div></section><div className="mt-5 grid items-start gap-5 lg:grid-cols-[270px_minmax(0,1fr)]"><aside className="card max-h-[calc(100vh-92px)] overflow-auto p-4 lg:sticky lg:top-20"><div className="mb-3 flex items-center gap-2 font-bold"><BookOpen size={17} className="text-[#008060]"/> İçindekiler</div><nav className="space-y-0.5">{headings.map((h,i)=><a key={`${h}-${i}`} href={`#${slug(h)}`} className="block rounded-lg px-3 py-2 text-sm leading-5 text-[#4a4d50] hover:bg-[#edf7f3] hover:text-[#006e52]">{h}</a>)}</nav></aside><main className="card min-w-0 px-6 py-7 sm:px-10 sm:py-9"><div className="mb-8 flex gap-3 rounded-xl border border-[#aee9d1] bg-[#f0fff9] p-4 text-sm leading-6 text-[#335c50]"><Lightbulb className="mt-0.5 shrink-0 text-[#008060]" size={19}/><p>Yeni başladıysanız önce “Sistemin temel çalışma akışı” bölümünü okuyun. İşlem sırasında takıldığınızda soldaki başlıklardan doğrudan ilgili ekrana geçebilirsiniz.</p></div>{renderMarkdown(markdown)}</main></div></div>}

export default function GuidePage() {
  const me = useQuery({queryKey:['session-user'],queryFn:()=>api<SessionUser>('/api/auth/me')});
  const allowed = !!me.data && ['Admin','Partner','Analyst'].includes(me.data.role);
  const guide = useQuery({queryKey:['guide',me.data?.id],enabled:allowed,staleTime:0,gcTime:0,queryFn:async()=>{
    const response = await fetch('/api/guide',{headers:{authorization:'Bearer '+token()},cache:'no-store'});
    if(response.status===401)logout();
    const body = await response.json();
    if(!response.ok)throw new Error(body.error ?? 'Rehber yüklenemedi.');
    return body as {markdown:string;updatedAt:string};
  }});
  useEffect(()=>{if(guide.data && window.location.hash){const id=decodeURIComponent(window.location.hash.slice(1));document.getElementById(id)?.scrollIntoView();}},[guide.data]);
  if(me.isError || guide.isError)return <div role="alert" className="card p-5"><p>{me.error?.message ?? guide.error?.message}</p><button className="mt-3 underline" onClick={()=>{void me.refetch();if(allowed)void guide.refetch();}}>Yeniden dene</button></div>;
  if(me.isPending || (allowed && guide.isPending))return <p role="status">Kullanım rehberi yükleniyor…</p>;
  if(!allowed)return <p>Bu rehber yalnız iç ekip hesaplarına açıktır.</p>;
  return guide.data ? <GuideContent {...guide.data}/> : null;
}
