"use client";
import Link from "next/link";
import Image from "next/image";
import {useEffect,useRef,useState} from "react";
import {usePathname,useRouter} from "next/navigation";
import {useQuery} from "@tanstack/react-query";
import {Bell,BookOpen,Building2,ChartNoAxesCombined,CircleDollarSign,FileChartColumn,Gauge,Handshake,History,LayoutDashboard,LogOut,Menu,Plus,Search,Settings,ShieldCheck,Users,X} from "lucide-react";
import {api,isSessionValid,logout,type SessionUser} from "@/lib/api";
import {turkce} from "@/lib/turkish";

const nav=[["Ana sayfa","/",LayoutDashboard],["İşlerim","/work",Bell],["Markalar","/brands",Building2],["Potansiyel markalar","/leads",Users],["Değerlendirmeler","/evaluations",Gauge],["Anlaşmalar","/deals",Handshake],["Aylık sonuçlar","/performance",ChartNoAxesCombined],["Hakedişler","/commissions",CircleDollarSign],["Raporlar","/reports",FileChartColumn],["Karar kuralları","/rules",ShieldCheck],["İşlem geçmişi","/activity",History],["Kullanım rehberi","/guide",BookOpen]] as const;
type SearchResult={type:string;title:string;detail:string;href:string};type Task={kind:string;title:string;detail:string;href:string;priority:string};

export function AppShell({children}:{children:React.ReactNode}){
  const path=usePathname(); const router=useRouter();
  const me=useQuery({queryKey:["session-user"],queryFn:()=>api<SessionUser>("/api/auth/me"),enabled:path!=="/login",refetchInterval:path!=="/login"?30_000:false});
  useEffect(()=>{if(path!=="/login"&&!isSessionValid())router.replace("/login")},[path,router]);
  if(path==="/login")return <>{children}</>;
  if(me.isPending)return <p className="p-6" role="status">Hesap yetkisi kontrol ediliyor…</p>;
  if(me.isError)return <div className="p-6"><p role="alert">Hesap bilgisi alınamadı. Bağlantınızı kontrol edin.</p><button className="mt-3 underline" onClick={()=>void me.refetch()}>Yeniden dene</button><button className="ml-4 underline" onClick={logout}>Çıkış yap</button></div>;
  if(me.data?.role==="BrandClient")return <CustomerShell name={me.data.name}>{children}</CustomerShell>;
  if(path==="/portal")return <div className="p-6">Bu alan marka yetkililerine ayrılmıştır. <Link className="underline" href="/portal-management">Portal yönetimini aç</Link></div>;
  return <InternalShell>{children}</InternalShell>;
}
function CustomerShell({children,name}:{children:React.ReactNode;name:string}){
  const path=usePathname();const router=useRouter();
  useEffect(()=>{if(path!=="/portal")router.replace("/portal")},[path,router]);
  return <div className="min-h-screen"><header className="flex flex-wrap items-center justify-between gap-3 border-b bg-white px-5 py-4 print:hidden"><Link className="flex items-center gap-3 font-semibold" href="/portal"><Image src="/ovo-logo.svg" alt="OVO" width={40} height={40} className="rounded-lg bg-[#101112] p-1"/>Marka portalı</Link><div className="flex items-center gap-3 text-sm"><span>{name}</span><button className="underline" onClick={logout}>Çıkış yap</button></div></header><main className="mx-auto max-w-5xl p-4 sm:p-6">{path==="/portal"?children:<p>Marka portalına yönlendiriliyorsunuz…</p>}</main></div>;
}
function InternalShell({children}:{children:React.ReactNode}){
  const path=usePathname();const router=useRouter();const[menu,setMenu]=useState(false);const[search,setSearch]=useState("");const[searchOpen,setSearchOpen]=useState(false);const[tasksOpen,setTasksOpen]=useState(false);const input=useRef<HTMLInputElement>(null);const evaluationDirty=useRef(false);
  useEffect(()=>{if(path==="/login")return;if(!isSessionValid()){localStorage.removeItem("ovo_token");router.replace("/login")}},[path,router]);
  useEffect(()=>{const key=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==="k"){e.preventDefault();setSearchOpen(true);input.current?.focus()}if(e.key==="Escape"){setSearchOpen(false);setTasksOpen(false);setMenu(false)}};window.addEventListener("keydown",key);return()=>window.removeEventListener("keydown",key)},[]);
  useEffect(()=>{evaluationDirty.current=false;if(!path.startsWith("/evaluations/"))return;const changed=()=>{evaluationDirty.current=true};const leaving=(event:BeforeUnloadEvent)=>{if(evaluationDirty.current)event.preventDefault()};const link=(event:MouseEvent)=>{const target=(event.target as HTMLElement).closest("a");if(target&&evaluationDirty.current&&!window.confirm("Kaydedilmemiş değişiklikleriniz var. Bu sayfadan ayrılmak istediğinize emin misiniz?")){event.preventDefault();event.stopPropagation()}};document.addEventListener("input",changed);document.addEventListener("click",link,true);window.addEventListener("beforeunload",leaving);return()=>{document.removeEventListener("input",changed);document.removeEventListener("click",link,true);window.removeEventListener("beforeunload",leaving)}},[path]);
  const results=useQuery({queryKey:["global-search",search],queryFn:()=>api<SearchResult[]>(`/api/search?q=${encodeURIComponent(search)}`),enabled:search.trim().length>=2});
  const tasks=useQuery({queryKey:["tasks"],queryFn:()=>api<Task[]>("/api/tasks"),enabled:tasksOpen,refetchInterval:tasksOpen?60_000:false});
  const me=useQuery({queryKey:["session-user"],queryFn:()=>api<SessionUser>("/api/auth/me"),enabled:path!=="/login",refetchInterval:path!=="/login"?30_000:false});
  if(path==="/login")return <>{children}</>;
  return <div className="min-h-screen">{menu&&<button aria-label="Menüyü kapat" className="fixed inset-0 z-40 bg-black/30 lg:hidden" onClick={()=>setMenu(false)}/>}<aside className={`fixed inset-y-0 left-0 z-50 w-[240px] border-r border-[#dfe3e8] bg-[#f7f7f8] p-3 transition-transform lg:translate-x-0 ${menu?"translate-x-0":"-translate-x-full"}`}>
    <div className="mb-5 flex items-center gap-3 px-2 py-2"><div className="grid h-9 w-9 place-items-center rounded-lg bg-[#101112] p-1"><Image src="/ovo-logo.svg" alt="OVO" width={32} height={32} priority/></div><div className="min-w-0"><div className="font-bold tracking-tight">OVO Growth OS</div><div className="text-xs text-[#6d7175]">Büyüme ve iş ortaklığı merkezi</div></div><button onClick={()=>setMenu(false)} aria-label="Menüyü kapat" className="ml-auto p-1 lg:hidden"><X size={19}/></button></div>
    <nav className="max-h-[calc(100dvh-240px)] space-y-1 overflow-y-auto">{nav.map(([label,href,Icon])=>{const active=href==="/"?path==="/":path.startsWith(href);return <Link key={href} href={href} onClick={()=>setMenu(false)} className={`flex items-center gap-3 rounded-lg px-3 py-2 text-sm font-medium ${active?"bg-[#e3e5e7] text-[#202223]":"text-[#4a4d50] hover:bg-[#eceeef]"}`}><Icon size={17}/>{label}</Link>})}{me.data?.role!=="Analyst"&&<Link href="/portal-management" onClick={()=>setMenu(false)} className={`flex items-center gap-3 rounded-lg px-3 py-2 text-sm font-medium ${path==="/portal-management"?"bg-[#e3e5e7]":"text-[#4a4d50]"}`}><Users size={17}/>Müşteri portalı</Link>}</nav>
    <div className="absolute inset-x-3 bottom-3 border-t border-[#dfe3e8] pt-3"><Link href="/settings" className="flex items-center gap-3 rounded-lg px-3 py-2 text-sm text-[#4a4d50]"><Settings size={17}/>Ayarlar</Link><button onClick={logout} className="flex w-full items-center gap-3 rounded-lg px-3 py-2 text-sm text-[#4a4d50]"><LogOut size={17}/>Çıkış yap</button><div className="mt-2 flex items-center gap-3 px-3"><div className="grid h-8 w-8 shrink-0 place-items-center rounded-full bg-[#d4e8df] text-xs font-bold text-[#006e52]">OVO</div><div className="min-w-0"><div className="truncate text-sm font-semibold">{me.data?.name??"Hesap bilgisi yükleniyor…"}</div><div className="text-xs text-[#6d7175]">{me.data?turkce(me.data.role):""}</div></div></div></div>
  </aside><div className="min-h-screen lg:ml-[240px]"><header className="sticky top-0 z-30 flex h-16 items-center gap-3 border-b border-[#dfe3e8] bg-white/95 px-4 backdrop-blur lg:px-5"><button className="rounded-lg p-2 lg:hidden" onClick={()=>setMenu(true)} aria-label="Menüyü aç"><Menu size={21}/></button>
    <div className="relative min-w-0 flex-1 max-w-[520px]"><label className="flex items-center gap-2 rounded-lg border border-[#c9cccf] bg-[#f6f6f7] px-3 py-2 text-sm"><Search size={16} className="shrink-0 text-[#6d7175]"/><input ref={input} value={search} onFocus={()=>setSearchOpen(true)} onChange={e=>{setSearch(e.target.value);setSearchOpen(true)}} className="min-w-0 flex-1 bg-transparent outline-none" placeholder="Marka, anlaşma veya değerlendirme ara…"/><span className="hidden rounded border bg-white px-1.5 text-xs text-[#6d7175] sm:block">⌘ K</span></label>{searchOpen&&search.trim().length>=2&&<div className="absolute left-0 right-0 top-12 max-h-[420px] overflow-auto rounded-xl border bg-white p-2 shadow-xl">{results.isLoading?<p className="p-3 text-sm text-[#6d7175]">Aranıyor…</p>:results.data?.length?results.data.map((x,i)=><Link href={x.href} key={`${x.href}-${i}`} className="block rounded-lg px-3 py-2 hover:bg-[#f3f4f5]"><div className="text-xs font-semibold text-[#008060]">{turkce(x.type)}</div><div className="text-sm font-semibold">{x.title}</div><div className="text-xs text-[#6d7175]">{turkce(x.detail)}</div></Link>):<p className="p-3 text-sm text-[#6d7175]">Eşleşen kayıt bulunamadı.</p>}</div>}</div>
    <div className="ml-auto flex items-center gap-1.5"><Link href="/evaluations/new" className="hidden items-center gap-1.5 rounded-lg bg-[#303030] px-3 py-2 text-sm font-semibold text-white sm:flex"><Plus size={15}/>Yeni değerlendirme</Link><div className="relative"><button onClick={()=>setTasksOpen(x=>!x)} className="relative rounded-lg p-2 hover:bg-[#f1f2f3]" aria-label="Yapılacak işler"><Bell size={19}/>{tasks.data?.length?<span className="absolute right-1 top-1 h-2 w-2 rounded-full bg-[#d72c0d]"/>:null}</button>{tasksOpen&&<div className="absolute right-0 top-12 w-[min(380px,calc(100vw-24px))] rounded-xl border bg-white p-2 shadow-xl"><div className="flex items-center justify-between px-2 py-2"><Link href="/work" onClick={()=>setTasksOpen(false)} className="font-bold underline">İşlerim ve hatırlatmalar</Link><span className="text-xs text-[#6d7175]">{tasks.data?.length??0} kayıt</span></div><div className="max-h-[480px] overflow-auto">{tasks.isLoading?<p className="p-3 text-sm">Yükleniyor…</p>:tasks.data?.length?tasks.data.map((x,i)=><Link href={x.href} key={`${x.href}-${i}`} className="block rounded-lg border-t px-3 py-3 hover:bg-[#f7f7f8]"><div className="flex items-center justify-between gap-2"><span className="text-xs font-semibold text-[#008060]">{x.kind}</span>{x.priority==="Yüksek"&&<span className="rounded-full bg-[#fed3d1] px-2 py-0.5 text-xs text-[#8e1f0b]">Öncelikli</span>}</div><div className="mt-1 text-sm font-semibold">{x.title}</div><div className="mt-1 text-xs text-[#6d7175]">{x.detail}</div></Link>):<p className="p-6 text-center text-sm text-[#6d7175]">Size gösterilecek hatırlatma yok. Tüm işleri İşlerim sayfasından kontrol edebilirsiniz.</p>}</div></div>}</div></div></header><main className="mx-auto max-w-[1440px] px-4 py-5 sm:px-6 sm:py-6">{children}</main></div></div>;
}
