'use client';

import { FormEvent, useState } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { api } from '@/lib/api';
import { notify } from '@/components/feedback';
import { Badge, Card, PageHeader } from '@/components/ui/core';
import { turkce } from '@/lib/turkish';

type Template = { id:string; name:string; description:string; enabled:boolean; displayOrder:number; dealType:string; contractMonths:number; monthlyRetainer:number; minimumMonthlyFee:number; revenueShareRate:number; incrementalRate:number; profitShareRate:number; commissionTiersJson:string };
const empty = { name:'', description:'', enabled:true, displayOrder:1, dealType:'MinimumFeePlusRevenueShare', contractMonths:12, monthlyRetainer:0, minimumMonthlyFee:0, revenueShareRate:0, incrementalRate:0, profitShareRate:0 };
const types=['FlatRevenueShare','TieredRevenueShare','RetainerPlusRevenueShare','MinimumFeePlusRevenueShare','IncrementalRevenueShare','RetainerPlusIncrementalRevenueShare','ContributionProfitShare','FixedRetainer'];

export default function Page(){
 const qc=useQueryClient(); const {data=[]}=useQuery({queryKey:['deal-templates'],queryFn:()=>api<Template[]>('/api/deal-templates')}); const [selected,setSelected]=useState<Template|null>(null); const [form,setForm]=useState(empty);
 function edit(t:Template){setSelected(t);setForm({...t,revenueShareRate:t.revenueShareRate*100,incrementalRate:t.incrementalRate*100,profitShareRate:t.profitShareRate*100});}
 function change(k:string,v:string|boolean){setForm(x=>({...x,[k]:v}));}
 async function submit(e:FormEvent){e.preventDefault();const payload={...form,revenueShareRate:Number(form.revenueShareRate)/100,incrementalRate:Number(form.incrementalRate)/100,profitShareRate:Number(form.profitShareRate)/100,commissionTiers: selected?JSON.parse(selected.commissionTiersJson||'[]'):[]};await api(selected?'/api/deal-templates/'+selected.id:'/api/deal-templates',{method:selected?'PUT':'POST',body:JSON.stringify(payload)});notify('Anlaşma şablonu kaydedildi.');setSelected(null);setForm(empty);await qc.invalidateQueries({queryKey:['deal-templates']});}
 return <><PageHeader title="Anlaşma şablonları" description="Değerlendirme sonrası üretilecek anlaşma seçeneklerini yönetin." action={<button className="rounded-lg bg-[#303030] px-4 py-2 text-sm font-semibold text-white" onClick={()=>{setSelected(null);setForm(empty)}}>Yeni şablon</button>}/><div className="grid gap-4 xl:grid-cols-[1fr_420px]"><div className="space-y-3">{data.map(t=><Card key={t.id} className="p-5"><div className="flex items-start justify-between gap-3"><div><h2 className="font-semibold">{t.name}</h2><p className="mt-1 text-sm text-[#6d7175]">{t.description||'Açıklama yok'}</p></div><Badge tone={t.enabled?'green':'gray'}>{t.enabled?'Etkin':'Pasif'}</Badge></div><div className="mt-4 grid grid-cols-3 gap-3 text-sm"><div><span className="text-[#6d7175]">Model</span><strong className="block">{turkce(t.dealType)}</strong></div><div><span className="text-[#6d7175]">Süre</span><strong className="block">{t.contractMonths} ay</strong></div><div><span className="text-[#6d7175]">Gelir payı</span><strong className="block">{(t.revenueShareRate*100).toFixed(2)}%</strong></div></div><button className="mt-4 rounded-lg border px-3 py-1.5 text-sm font-semibold" onClick={()=>edit(t)}>Düzenle</button></Card>)}</div><Card className="h-fit p-5"><h2 className="font-semibold">{selected?'Şablonu düzenle':'Yeni şablon'}</h2><form onSubmit={submit} className="mt-4 space-y-3">{[['name','Şablon adı'],['description','Açıklama']].map(([k,l])=><label key={k}><span className="label">{l}</span><input className="input mt-1.5" required={k==='name'} value={String(form[k as keyof typeof form]??'')} onChange={e=>change(k,e.target.value)}/></label>)}<label><span className="label">Anlaşma modeli</span><select className="input mt-1.5" value={form.dealType} onChange={e=>change('dealType',e.target.value)}>{types.map(x=><option key={x} value={x}>{turkce(x)}</option>)}</select></label>{[['contractMonths','Sözleşme süresi (ay)'],['displayOrder','Sıra'],['monthlyRetainer','Aylık sabit ücret'],['minimumMonthlyFee','Asgari aylık ücret'],['revenueShareRate','Gelir payı (%)'],['incrementalRate','Büyüme payı (%)'],['profitShareRate','Kâr payı (%)']].map(([k,l])=><label key={k}><span className="label">{l}</span><input className="input mt-1.5" type="number" step="any" value={String(form[k as keyof typeof form])} onChange={e=>change(k,e.target.value)}/></label>)}<label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.enabled} onChange={e=>change('enabled',e.target.checked)}/> Şablon etkin</label><button className="w-full rounded-lg bg-[#303030] px-4 py-2 text-sm font-semibold text-white">Kaydet</button></form></Card></div></>;
}
