'use client';
import { FormEvent, ReactNode } from 'react';
import { useParams } from 'next/navigation';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { api, money, percent } from '@/lib/api';
import { notify } from '@/components/feedback';
import { ConditionsPanel, Condition, DocumentsPanel } from '@/components/record-panels';
import { Badge, Card, PageHeader } from '@/components/ui/core';
import { turkce } from '@/lib/turkish';
import { InvestmentLedger } from '@/components/operating-costs';

type Deal = { id:string; name:string; status:string; dealType:string; brand:{name:string}; contractMonths:number; baselineRevenue:number; baselinePeriodStart?:string; baselinePeriodEnd?:string; baselineCalculationMethod:string; monthlyRetainer:number; minimumMonthlyFee:number; revenueShareRate:number; incrementalRate:number; profitShareRate:number; commissionTiersJson:string; setupInvestment:number; estimatedMonthlyInternalCost:number; startDate?:string; endDate?:string; statusReason:string; conditions:Condition[] };
const dealTypes=['FlatRevenueShare','TieredRevenueShare','RetainerPlusRevenueShare','MinimumFeePlusRevenueShare','IncrementalRevenueShare','RetainerPlusIncrementalRevenueShare','ContributionProfitShare','FixedRetainer'];
const baseMethods=['Manual','Trailing3MonthAverage','Trailing6MonthAverage','Trailing12MonthAverage'];

export default function Page(){
 const {id}=useParams<{id:string}>(); const qc=useQueryClient();
 const {data,error}=useQuery({queryKey:['deal',id],queryFn:()=>api<Deal>('/api/deals/'+id)});
 if(error)return <Card className="p-6 text-[#d72c0d]">{error.message}</Card>; if(!data)return <Card className="p-6">Anlaşma yükleniyor…</Card>; const d=data;
 const editable=['Draft','InternalReview','Proposed','Negotiation'].includes(d.status);
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const n=(x:string)=>Number(f.get(x));await api('/api/deals/'+id,{method:'PUT',body:JSON.stringify({name:f.get('name'),dealType:f.get('dealType'),contractMonths:n('contractMonths'),baselineRevenue:n('baselineRevenue'),baselinePeriodStart:f.get('baselinePeriodStart')||null,baselinePeriodEnd:f.get('baselinePeriodEnd')||null,baselineCalculationMethod:f.get('baselineCalculationMethod'),monthlyRetainer:n('monthlyRetainer'),minimumMonthlyFee:n('minimumMonthlyFee'),revenueShareRate:n('revenueShareRate')/100,incrementalRate:n('incrementalRate')/100,profitShareRate:n('profitShareRate')/100,commissionTiers:JSON.parse(d.commissionTiersJson||'[]'),setupInvestment:n('setupInvestment'),estimatedMonthlyInternalCost:n('estimatedMonthlyInternalCost')})});notify('Anlaşma koşulları kaydedildi.');await qc.invalidateQueries({queryKey:['deal',id]});}
 async function action(name:string,body?:object){await api('/api/deals/'+id+'/'+name,{method:'POST',body:body?JSON.stringify(body):undefined});notify('Anlaşma durumu güncellendi.');await Promise.all([qc.invalidateQueries({queryKey:['deal',id]}),qc.invalidateQueries({queryKey:['deals']})]);}
 function reasonAction(name:string){const reason=prompt('Bu işlemin nedenini yazın:');if(reason?.trim())void action(name,{reason});}
 return <><PageHeader title={d.name} description={`${d.brand.name} · ${turkce(d.dealType)}`} action={<Badge tone={d.status==='Active'?'green':['Terminated','Expired'].includes(d.status)?'red':'blue'}>{turkce(d.status)}</Badge>}/><div className="mb-4 flex flex-wrap gap-2"><Lifecycle status={d.status} action={action} reasonAction={reasonAction}/></div><div className="grid gap-4 xl:grid-cols-[1.4fr_1fr]"><Card className="p-5"><h2 className="font-semibold">Ticari koşullar</h2><form onSubmit={save} className="mt-4 grid gap-4 md:grid-cols-2"><Field name="name" label="Anlaşma adı" value={d.name} disabled={!editable} required/>{[['contractMonths','Sözleşme süresi (ay)',d.contractMonths],['baselineRevenue','Baz ciro',d.baselineRevenue],['monthlyRetainer','Aylık sabit ücret',d.monthlyRetainer],['minimumMonthlyFee','Asgari aylık ücret',d.minimumMonthlyFee],['revenueShareRate','Gelir payı (%)',d.revenueShareRate*100],['incrementalRate','Büyüme payı (%)',d.incrementalRate*100],['profitShareRate','Kâr payı (%)',d.profitShareRate*100],['setupInvestment','Kurulum yatırımı',d.setupInvestment],['estimatedMonthlyInternalCost','Tahmini aylık iç maliyet',d.estimatedMonthlyInternalCost]].map(([n,l,v])=><Field key={String(n)} name={String(n)} label={String(l)} value={Number(v)} disabled={!editable} type="number"/>)}<Select name="dealType" label="Anlaşma modeli" value={d.dealType} options={dealTypes} disabled={!editable}/><Select name="baselineCalculationMethod" label="Baz hesaplama yöntemi" value={d.baselineCalculationMethod} options={baseMethods} disabled={!editable}/><Field name="baselinePeriodStart" label="Baz dönem başlangıcı" value={d.baselinePeriodStart??''} disabled={!editable} type="date"/><Field name="baselinePeriodEnd" label="Baz dönem bitişi" value={d.baselinePeriodEnd??''} disabled={!editable} type="date"/>{editable&&<div className="flex justify-end border-t pt-4 md:col-span-2"><button className="rounded-lg bg-[#303030] px-4 py-2 text-sm font-semibold text-white">Koşulları kaydet</button></div>}</form>{!editable&&<div className="mt-4 grid gap-3 border-t pt-4 text-sm sm:grid-cols-3"><Summary l="Başlangıç" v={d.startDate||'—'}/><Summary l="Bitiş" v={d.endDate||'—'}/><Summary l="Aylık güvence" v={money(d.minimumMonthlyFee)}/></div>}</Card><div className="space-y-4"><ConditionsPanel conditions={d.conditions}/><Card className="p-5"><h2 className="font-semibold">Kısa özet</h2><Row l="Gelir payı" v={percent(d.revenueShareRate)}/><Row l="Aylık sabit ücret" v={money(d.monthlyRetainer)}/><Row l="Kurulum yatırımı" v={money(d.setupInvestment)}/>{d.statusReason&&<p className="mt-3 border-t pt-3 text-sm text-[#6d7175]">{d.statusReason}</p>}</Card></div></div><div className="mt-4"><DocumentsPanel entityType="Deal" entityId={id}/></div><InvestmentLedger id={id}/></>;
}
function Lifecycle({status,action,reasonAction}:{status:string;action:(x:string)=>Promise<void>;reasonAction:(x:string)=>void}){return <>{status==='Draft'&&<Action onClick={()=>action('review')}>İç incelemeye gönder</Action>}{status==='InternalReview'&&<Action onClick={()=>action('propose')}>Markaya öner</Action>}{status==='Proposed'&&<Action onClick={()=>action('negotiate')} secondary>Görüşmeye al</Action>}{['Draft','InternalReview','Proposed','Negotiation'].includes(status)&&<Action onClick={()=>action('accept')} positive>Kabul edildi</Action>}{status==='Accepted'&&<Action onClick={()=>action('activate')} positive>Anlaşmayı etkinleştir</Action>}{status==='Active'&&<><Action onClick={()=>reasonAction('renew')} secondary>Yenileme taslağı oluştur</Action><Action onClick={()=>reasonAction('terminate')} danger>Anlaşmayı sonlandır</Action><Action onClick={()=>reasonAction('expire')} secondary>Süresi doldu</Action></>}</>}
function Action({children,onClick,secondary,positive,danger}:{children:ReactNode;onClick:()=>void;secondary?:boolean;positive?:boolean;danger?:boolean}){const c=danger?'border border-[#f1aaa4] text-[#8e1f0b]':positive?'bg-[#008060] text-white':secondary?'border':'bg-[#303030] text-white';return <button className={`rounded-lg px-4 py-2 text-sm font-semibold ${c}`} onClick={onClick}>{children}</button>}
function Field({name,label,value,disabled,type='text',required}:{name:string;label:string;value:string|number;disabled:boolean;type?:string;required?:boolean}){return <label><span className="label">{label}</span><input className="input mt-1.5 disabled:bg-[#f3f4f5]" name={name} type={type} step={type==='number'?'any':undefined} defaultValue={value} disabled={disabled} required={required}/></label>}
function Select({name,label,value,options,disabled}:{name:string;label:string;value:string;options:string[];disabled:boolean}){return <label><span className="label">{label}</span><select className="input mt-1.5" name={name} defaultValue={value} disabled={disabled}>{options.map(x=><option key={x} value={x}>{turkce(x)}</option>)}</select></label>}
function Summary({l,v}:{l:string;v:string}){return <div><span className="text-[#6d7175]">{l}</span><strong className="block">{v}</strong></div>};function Row({l,v}:{l:string;v:string}){return <div className="mt-3 flex justify-between text-sm"><span>{l}</span><strong>{v}</strong></div>}
