'use client';
import { FormEvent, useState } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { api, moneyPrecise, type SessionUser } from '@/lib/api';
import { Card, PageHeader } from '@/components/ui/core';
import { DocumentsPanel } from '@/components/record-panels';
import { PortalReportView, type PortalSnapshot } from '@/components/portal-report';

type Brand={id:string;name:string}; type Account={id:string;name:string;email:string;isActive:boolean};
type Period={id:string;year:number;month:number;currency:string};type Report={id:string;year:number;month:number;version:number;revokedAt:string|null};
type SharedDocument={id:string;documentId:string;fileName:string;revokedAt:string|null};
type Question={id:string;reportId:string;question:string;answer:string};
const button='rounded-lg border px-3 py-2 text-sm disabled:opacity-50';
export default function Page(){
  const me=useQuery({queryKey:['session-user'],queryFn:()=>api<SessionUser>('/api/auth/me')});
  const allowed=me.data?.role==='Admin'||me.data?.role==='Partner';
  const brands=useQuery({queryKey:['portal-brands'],queryFn:()=>api<{items:Brand[]}>('/api/brands?pageSize=100'),enabled:allowed});
  const[brandId,setBrandId]=useState('');
  if(me.isPending)return <p>Hesap yetkisi kontrol ediliyor…</p>;
  if(!allowed)return <p>Portal paylaşımını yalnız yönetici veya ortak yönetebilir.</p>;
  return <><PageHeader title="Müşteri portalı yönetimi" description="Rapor ve belgeler kendiliğinden paylaşılmaz. Bu ekrandan açıkça yayımladığınız içerik marka yetkililerine açılır."/><label className="mb-4 block text-sm">Marka seçin<select className="input mt-2 max-w-lg" value={brandId} onChange={e=>setBrandId(e.target.value)}><option value="">Marka seçin</option>{brands.data?.items.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label>{brands.isPending&&<p>Markalar yükleniyor…</p>}{brands.isError&&<p role="alert">{brands.error.message}</p>}{brandId&&<Management key={brandId} brandId={brandId} admin={me.data?.role==='Admin'}/>}</>;
}
function Management({brandId,admin}:{brandId:string;admin:boolean}){
  const qc=useQueryClient();const root=`/api/portal-management/brands/${brandId}`;
  const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[notice,setNotice]=useState('');const[periodId,setPeriodId]=useState('');const[reportId,setReportId]=useState('');
  const accounts=useQuery({queryKey:['portal-admin',brandId,'accounts'],queryFn:()=>api<Account[]>(root+'/accounts'),enabled:admin});
  const periods=useQuery({queryKey:['portal-admin',brandId,'periods'],queryFn:()=>api<Period[]>(root+'/periods')});
  const reports=useQuery({queryKey:['portal-admin',brandId,'reports'],queryFn:()=>api<Report[]>(root+'/reports')});
  const documents=useQuery({queryKey:['documents','Brand',brandId],queryFn:()=>api<{id:string;fileName:string}[]>(`/api/documents/Brand/${brandId}`)});
  const shares=useQuery({queryKey:['portal-admin',brandId,'documents'],queryFn:()=>api<SharedDocument[]>(root+'/documents')});
  const questions=useQuery({queryKey:['portal-admin',brandId,'questions'],queryFn:()=>api<Question[]>(root+'/questions'),refetchInterval:30000});
  const selected=periods.data?.find(p=>p.id===periodId);
  const preview=useQuery({queryKey:['portal-preview',brandId,periodId],queryFn:()=>api<{current:PortalSnapshot['metrics']|null;currency:string}>(`/api/reports/brands/${brandId}?year=${selected!.year}&month=${selected!.month}&currency=${encodeURIComponent(selected!.currency)}&scope=Closed&audience=brand`),enabled:!!selected});
  const report=useQuery({queryKey:['portal-admin',brandId,'report',reportId],queryFn:()=>api<PortalSnapshot>(root+'/reports/'+reportId),enabled:!!reportId});
  async function act(path:string,body?:unknown,method='POST'){
    if(busy)return;setBusy(true);setError('');setNotice('');
    try{await api(root+path,{method,body:body===undefined?undefined:JSON.stringify(body)});await qc.invalidateQueries({queryKey:['portal-admin',brandId]});setNotice('İşlem kaydedildi.');return true;}
    catch(e){setError(e instanceof Error?e.message:'İşlem tamamlanamadı.');return false;}finally{setBusy(false);}
  }
  async function saveAccount(e:FormEvent<HTMLFormElement>,id?:string){e.preventDefault();const form=e.currentTarget;const f=new FormData(form);if(!confirm('Bu müşteri hesabının erişim bilgilerini kaydetmek istiyor musunuz? Değişiklik mevcut oturumlarını kapatır.'))return;const ok=await act('/accounts'+(id?'/'+id:''),{name:f.get('name'),email:f.get('email'),password:f.get('password')||null,isActive:f.get('active')==='on'},id?'PUT':'POST');if(ok){if(id){const input=form.elements.namedItem('password') as HTMLInputElement;input.value='';}else form.reset();}}
  const queryError=[periods.error,reports.error,documents.error,shares.error,questions.error,admin?accounts.error:null].find(Boolean);
  return <div className="space-y-4">{error&&<p role="alert" className="text-red-700">{error}</p>}{queryError&&<p role="alert">{queryError.message}</p>}{notice&&<p role="status">{notice}</p>}
    <Card className="space-y-3 p-5"><h2 className="font-semibold">1. Marka yetkilileri</h2><p className="text-sm">Her müşteri hesabı yalnız bu markaya bağlıdır; sonradan başka markaya taşınmaz. Şifreyi güvenli bir kanaldan iletin. Davet e-postası otomatik gönderilmez. Hesabı kapatmak sonraki istekte mevcut oturumunu da geçersiz kılar.</p>{admin?<>{accounts.isPending&&<p>Hesaplar yükleniyor…</p>}{accounts.data?.map(a=><details key={a.id} className="rounded-lg border p-3"><summary className="cursor-pointer text-sm">{a.name} · {a.email} · {a.isActive?'Erişim açık':'Erişim kapalı'}</summary><AccountForm account={a} busy={busy} onSubmit={e=>void saveAccount(e,a.id)}/></details>)}<details className="rounded-lg border p-3"><summary className="cursor-pointer">Yeni müşteri hesabı oluştur</summary><AccountForm busy={busy} onSubmit={e=>void saveAccount(e)}/></details></>:<p className="text-sm">Hesap açma, kapatma ve şifre yenileme işlemlerini yönetici yapar.</p>}</Card>
    <Card className="space-y-3 p-5"><h2 className="font-semibold">2. Dönem raporunu yayımla</h2><p className="text-sm">Yalnız kapanmış dönemler yayımlanabilir. Yayımlama, o andaki marka raporunu yeni bir sürüm olarak saklar; iç maliyetler ve iç notlar dahil edilmez. Sonraki değişiklikler önceki sürümü değiştirmez. Eski sürümleri gerekirse ayrıca geri çekin.</p><label className="block text-sm">Yayımlanacak dönem<select className="input mt-1" value={periodId} disabled={busy} onChange={e=>setPeriodId(e.target.value)}><option value="">Dönem seçin</option>{periods.data?.map(p=><option key={p.id} value={p.id}>{p.month}/{p.year}</option>)}</select></label>{!periods.isPending&&!periods.data?.length&&<p className="text-sm">Yayımlanabilecek kapanmış dönem yok.</p>}{selected&&preview.isPending&&<p>Ön izleme yükleniyor…</p>}{preview.isError&&<p role="alert">{preview.error.message}</p>}{selected&&preview.data?.current&&<div className="rounded-lg border p-3 text-sm"><p className="font-semibold">Yayımlama öncesi kontrol</p><p>Net ciro: {moneyPrecise(preview.data.current.netRevenue,preview.data.currency)}</p><p>OVO hakedişi: {moneyPrecise(preview.data.current.ovoFee,preview.data.currency)}</p><p>Markaya kalan katkı: {moneyPrecise(preview.data.current.brandContribution,preview.data.currency)}</p><p className="mt-2">Yayımlama anında güncel kapanmış kayıt yeniden okunur. Oluşan sürümü aşağıdan açıp kontrol edebilirsiniz.</p></div>}<button className={button} disabled={busy||!selected||!preview.data?.current||preview.isError||preview.isFetching} onClick={()=>{if(confirm('Bu dönemin marka raporu, erişimi açık tüm marka yetkililerine yeni bir sürüm olarak gösterilsin mi?'))void act('/reports',{performanceId:periodId});}}>Markayla paylaş</button>
    <h3 className="font-semibold">Yayımlanan sürümler</h3>{reports.isPending&&<p>Raporlar yükleniyor…</p>}{reports.data?.map(r=><div key={r.id} className="flex flex-wrap items-center gap-3 rounded-lg border p-3 text-sm"><button className="underline" onClick={()=>setReportId(r.id)}>{r.month}/{r.year} · Sürüm {r.version} · {r.revokedAt?'Geri çekildi':'Paylaşım açık'}</button>{!r.revokedAt&&<button className={button} disabled={busy} onClick={()=>{if(confirm('Bu rapor sürümünün portal erişimi kapatılsın mı? Daha önce indirilen dosyalar silinemez.'))void act(`/reports/${r.id}/revoke`);}}>Paylaşımı geri çek</button>}</div>)}{reportId&&report.isPending&&<p>Rapor açılıyor…</p>}{report.isError&&<p role="alert">{report.error.message}</p>}{report.data&&<PortalReportView data={report.data}/>}</Card>
    <DocumentsPanel entityType="Brand" entityId={brandId}/>
    <Card className="space-y-3 p-5"><h2 className="font-semibold">3. Belgeleri ayrı ayrı paylaş</h2><p className="text-sm">Yukarıda yüklenen belgeler varsayılan olarak özeldir. İlk sürümde yalnız doğrudan markaya eklenen belgeler paylaşılır. Dosyayı açıp içindeki bilgilerin markayla paylaşılabileceğini kontrol edin; dosya adı ve içeriği müşteriye görünür, iç açıklama notu görünmez.</p>{documents.isPending&&<p>Belgeler yükleniyor…</p>}{documents.data?.map(d=>{const shared=shares.data?.find(s=>s.documentId===d.id&&!s.revokedAt);return <div className="flex flex-wrap items-center gap-3 rounded-lg border p-3 text-sm" key={d.id}><span className="min-w-0 break-all">{d.fileName}</span><button disabled={busy||shares.isPending||shares.isError} className={button} onClick={()=>{if(confirm(shared?'Bu belgenin portal erişimi kapatılsın mı? İndirilen kopyalar silinemez.':'Bu dosyanın içeriğini kontrol ettiniz mi? Bu markanın tüm etkin müşteri hesapları dosyayı indirebilecek.'))void act(shared?`/documents/${shared.id}/revoke`:'/documents',shared?undefined:{documentId:d.id});}}>{shared?'Belge paylaşımını kapat':'Belgeyi paylaş'}</button></div>})}{!documents.isPending&&!documents.data?.length&&<p className="text-sm">Önce yukarıdaki alandan markaya belge ekleyin.</p>}</Card>
    <Card className="space-y-3 p-5"><h2 className="font-semibold">4. Müşteri soruları</h2><p className="text-sm">Yanıt doğrudan müşteriye gösterilir; iç maliyet veya özel not yazmayın. Gönderilen yanıt daha sonra değiştirilemez.</p>{questions.isPending&&<p>Sorular yükleniyor…</p>}{questions.data?.map(q=><div className="rounded-lg border p-3 text-sm" key={q.id}><p className="whitespace-pre-wrap break-words font-semibold">{q.question}</p>{q.answer?<p className="mt-2 whitespace-pre-wrap break-words">{q.answer}</p>:<form className="mt-3 space-y-2" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(confirm('Bu yanıt müşteriye gönderilsin mi?'))void act(`/questions/${q.id}/answer`,{answer:f.get('answer')});}}><label className="block">Müşteriye yanıt<textarea required maxLength={4000} name="answer" rows={3} className="input mt-1" disabled={busy}/></label><button className={button} disabled={busy}>Yanıtı gönder</button></form>}</div>)}{!questions.isPending&&!questions.data?.length&&<p className="text-sm">Henüz müşteri sorusu yok.</p>}</Card>
  </div>;
}
function AccountForm({account,busy,onSubmit}:{account?:Account;busy:boolean;onSubmit:(e:FormEvent<HTMLFormElement>)=>void}){return <form className="mt-3 grid gap-3 sm:grid-cols-2" onSubmit={onSubmit}><label className="text-sm">Ad soyad<input required name="name" maxLength={160} defaultValue={account?.name} className="input mt-1" disabled={busy}/></label><label className="text-sm">E-posta<input required name="email" type="email" maxLength={320} defaultValue={account?.email} className="input mt-1" disabled={busy}/></label><label className="text-sm">{account?'Yeni şifre (değişmeyecekse boş bırakın)':'İlk giriş şifresi'}<input required={!account} name="password" type="password" minLength={10} maxLength={256} autoComplete="new-password" className="input mt-1" disabled={busy}/></label><label className="flex items-center gap-2 text-sm"><input name="active" type="checkbox" defaultChecked={account?.isActive??true} disabled={busy}/>Portal erişimi açık</label><button className={button} disabled={busy}>{account?'Hesabı güncelle':'Müşteri hesabını oluştur'}</button></form>;}
