'use client';
import { FormEvent, useState } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { api, moneyPrecise, type SessionUser } from '@/lib/api';
import { Card, EmptyState, ErrorState, LoadingState, PageHeader } from '@/components/ui/core';
import { useDialog } from '@/components/ui/modal';
import { DocumentsPanel } from '@/components/record-panels';
import { PortalReportView, downloadPortal, type PortalSnapshot } from '@/components/portal-report';
import { PortalConversations } from '@/components/portal-conversations';
import { PortalRequests, PortalReportFollowup } from '@/components/portal-cooperation';
import { AccountInvitation } from '@/components/account-invitation';
import { BrandMailPolicyPanel } from '@/components/brand-mail-policy';
import { PortalSubmissionList } from '@/components/portal-submission';

type Brand={id:string;name:string}; type Account={id:string;name:string;email:string;isActive:boolean;invitationPending:boolean};
type Period={id:string;year:number;month:number;currency:string};type Report={id:string;year:number;month:number;version:number;revokedAt:string|null};
type SharedDocument={id:string;documentId:string;fileName:string;revokedAt:string|null};
const button='rounded-lg border px-3 py-2 text-sm disabled:opacity-50';
export default function Page(){
  const me=useQuery({queryKey:['session-user'],queryFn:()=>api<SessionUser>('/api/auth/me')});
  const allowed=me.data?.role==='Admin'||me.data?.role==='Partner';
  const brands=useQuery({queryKey:['portal-brands'],queryFn:()=>api<{items:Brand[]}>('/api/brands?pageSize=100'),enabled:allowed});
  const[brandId,setBrandId]=useState('');
  if(me.isPending)return <LoadingState label="Hesap yetkisi kontrol ediliyor…" />;
  if(!allowed)return <EmptyState message="Portal paylaşımını yalnız yönetici veya ortak yönetebilir." />;
  return <><PageHeader title="Müşteri portalı yönetimi" description="Rapor ve belgeler kendiliğinden paylaşılmaz. Bu ekrandan açıkça yayımladığınız içerik marka yetkililerine açılır."/><label className="mb-4 block text-sm">Marka seçin<select className="input mt-2 max-w-lg" value={brandId} onChange={e=>setBrandId(e.target.value)}><option value="">Marka seçin</option>{brands.data?.items.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label>{brands.isPending&&<LoadingState label="Markalar yükleniyor…" />}{brands.isError&&<ErrorState message={brands.error.message} />}{brandId&&<Management key={brandId} brandId={brandId} admin={me.data?.role==='Admin'}/>}</>;
}
function Management({brandId,admin}:{brandId:string;admin:boolean}){
  const{confirm}=useDialog();
  const qc=useQueryClient();const root=`/api/portal-management/brands/${brandId}`;
  const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[notice,setNotice]=useState('');const[periodId,setPeriodId]=useState('');const[reportId,setReportId]=useState('');
  const accounts=useQuery({queryKey:['portal-admin',brandId,'accounts'],queryFn:()=>api<Account[]>(root+'/accounts'),enabled:admin});
  const periods=useQuery({queryKey:['portal-admin',brandId,'periods'],queryFn:()=>api<Period[]>(root+'/periods')});
  const reports=useQuery({queryKey:['portal-admin',brandId,'reports'],queryFn:()=>api<Report[]>(root+'/reports')});
  const documents=useQuery({queryKey:['documents','Brand',brandId],queryFn:()=>api<{id:string;fileName:string}[]>(`/api/documents/Brand/${brandId}`)});
  const shares=useQuery({queryKey:['portal-admin',brandId,'documents'],queryFn:()=>api<SharedDocument[]>(root+'/documents')});
  const selected=periods.data?.find(p=>p.id===periodId);
  const preview=useQuery({queryKey:['portal-preview',brandId,periodId],queryFn:()=>api<{current:PortalSnapshot['metrics']|null;currency:string}>(`/api/reports/brands/${brandId}?year=${selected!.year}&month=${selected!.month}&currency=${encodeURIComponent(selected!.currency)}&scope=Closed&audience=brand`),enabled:!!selected});
  const report=useQuery({queryKey:['portal-admin',brandId,'report',reportId],queryFn:()=>api<PortalSnapshot>(root+'/reports/'+reportId),enabled:!!reportId});
  async function act(path:string,body?:unknown,method='POST'){
    if(busy)return;setBusy(true);setError('');setNotice('');
    try{await api(root+path,{method,body:body===undefined?undefined:JSON.stringify(body)});await qc.invalidateQueries({queryKey:['portal-admin',brandId]});setNotice('İşlem kaydedildi.');return true;}
    catch(e){setError(e instanceof Error?e.message:'İşlem tamamlanamadı.');return false;}finally{setBusy(false);}
  }
  async function saveAccount(e:FormEvent<HTMLFormElement>,id?:string){e.preventDefault();const form=e.currentTarget;const f=new FormData(form);if(!(await confirm({title:'Müşteri hesabı',message:'Bu müşteri hesabının erişim bilgilerini kaydetmek istiyor musunuz? Değişiklik mevcut oturumlarını kapatır.',confirmLabel:'Kaydet'})))return;const ok=await act('/accounts'+(id?'/'+id:''),{name:f.get('name'),email:f.get('email'),password:f.get('password')||null,isActive:f.get('active')==='on'},id?'PUT':'POST');if(ok){if(id){const input=form.elements.namedItem('password') as HTMLInputElement;input.value='';}else form.reset();}}
  async function downloadPdf(){setError('');try{const open=(report.data as PortalSnapshot|undefined);await downloadPortal(`${root}/reports/${reportId}/pdf`,`rapor-v${open?.version??''}.pdf`);}catch(e){setError(e instanceof Error?e.message:'PDF indirilemedi.');}}
  const queryError=[periods.error,reports.error,documents.error,shares.error,admin?accounts.error:null].find(Boolean);
  return <div className="space-y-4">{error&&<p role="alert" className="text-red-700">{error}</p>}{queryError&&<ErrorState message={queryError.message} />}{notice&&<p role="status">{notice}</p>}
    <Card className="space-y-3 p-5"><h2 className="font-semibold">1. Marka yetkilileri</h2><p className="text-sm">Her müşteri hesabı yalnız bu markaya bağlıdır; sonradan başka markaya taşınmaz. Şifreyi kendiniz oluşturursanız güvenli bir kanaldan iletin. E-posta hizmeti açıksa aşağıdaki ayrı davet formu kullanılabilir. Bekleyen davette kişi şifresini bağlantıdan belirlemeden giriş yapamaz. Hesabı kapatmak sonraki istekte mevcut oturumunu da geçersiz kılar.</p>{admin?<>{accounts.isPending&&<LoadingState label="Hesaplar yükleniyor…" />}{accounts.data?.map(a=><details key={a.id} className="rounded-lg border p-3"><summary className="cursor-pointer text-sm">{a.name} · {a.email} · {!a.isActive?'Erişim kapalı':a.invitationPending?'Davet bekleniyor':'Erişim açık'}</summary><AccountForm account={a} busy={busy} onSubmit={e=>void saveAccount(e,a.id)}/></details>)}<details className="rounded-lg border p-3"><summary className="cursor-pointer">Yeni müşteri hesabı oluştur</summary><AccountForm busy={busy} onSubmit={e=>void saveAccount(e)}/></details></>:<p className="text-sm">Hesap açma ve kapatma işlemlerini yönetici yapar. Kişi şifresini giriş ekranından yenileyebilir.</p>}</Card>
    {admin&&<AccountInvitation brandId={brandId}/>}
    {admin&&reports.data&&<BrandMailPolicyPanel brandId={brandId} reports={reports.data}/>}
    <div id="portal-publish" className="scroll-mt-20" />
    <Card className="space-y-3 p-5"><h2 className="font-semibold">2. Dönem raporunu yayımla</h2><p className="text-sm">Yalnız kapanmış dönemler yayımlanabilir. Yayımlama, o andaki marka raporunu yeni bir sürüm olarak saklar; iç maliyetler ve iç notlar dahil edilmez. Sonraki değişiklikler önceki sürümü değiştirmez. Eski sürümleri gerekirse ayrıca geri çekin.</p><label className="block text-sm">Yayımlanacak dönem<select className="input mt-1" value={periodId} disabled={busy} onChange={e=>setPeriodId(e.target.value)}><option value="">Dönem seçin</option>{periods.data?.map(p=><option key={p.id} value={p.id}>{p.month}/{p.year}</option>)}</select></label>{!periods.isPending&&!periods.data?.length&&<EmptyState message="Yayımlanabilecek kapanmış dönem yok." />}{selected&&preview.isPending&&<LoadingState label="Ön izleme yükleniyor…" />}{preview.isError&&<ErrorState message={preview.error.message} />}{selected&&preview.data?.current&&<div className="rounded-lg border p-3 text-sm"><p className="font-semibold">Yayımlama öncesi kontrol</p><p>Net ciro: {moneyPrecise(preview.data.current.netRevenue,preview.data.currency)}</p><p>OVO hakedişi: {moneyPrecise(preview.data.current.ovoFee,preview.data.currency)}</p><p>Markaya kalan katkı: {moneyPrecise(preview.data.current.brandContribution,preview.data.currency)}</p><p className="mt-2">Yayımlama anında güncel kapanmış kayıt yeniden okunur. Oluşan sürümü aşağıdan açıp kontrol edebilirsiniz.</p></div>}<button className={button} disabled={busy||!selected||!preview.data?.current||preview.isError||preview.isFetching} onClick={async()=>{if(!(await confirm({title:'Raporu paylaş',message:'Bu dönemin marka raporu, erişimi açık tüm marka yetkililerine yeni bir sürüm olarak gösterilsin mi?',tone:'danger',confirmLabel:'Paylaş'})))return;void act('/reports',{performanceId:periodId});}}>Markayla paylaş</button>
    <h3 className="font-semibold">Yayımlanan sürümler</h3>{reports.isPending&&<LoadingState label="Raporlar yükleniyor…" />}{reports.data?.map(r=><div key={r.id} className="flex flex-wrap items-center gap-3 rounded-lg border p-3 text-sm"><button className="underline" onClick={()=>setReportId(r.id)}>{r.month}/{r.year} · Sürüm {r.version} · {r.revokedAt?'Geri çekildi':'Paylaşım açık'}</button>{!r.revokedAt&&<button className={button} disabled={busy} onClick={async()=>{if(!(await confirm({title:'Paylaşımı geri çek',message:'Bu rapor sürümünün portal erişimi kapatılsın mı? Daha önce indirilen dosyalar silinemez.',tone:'danger',confirmLabel:'Geri çek'})))return;void act(`/reports/${r.id}/revoke`);}}>Paylaşımı geri çek</button>}</div>)}{reportId&&report.isPending&&<LoadingState label="Rapor açılıyor…" />}{report.isError&&<ErrorState message={report.error.message} />}{report.data&&<><PortalReportView data={report.data}/><button className={button+' mt-2'} onClick={()=>void downloadPdf()}>Bu raporun PDF’ini indir</button></>}</Card>
    <DocumentsPanel entityType="Brand" entityId={brandId}/>
    <Card className="space-y-3 p-5"><h2 className="font-semibold">3. Belgeleri ayrı ayrı paylaş</h2><p className="text-sm">Yukarıda yüklenen belgeler varsayılan olarak özeldir. İlk sürümde yalnız doğrudan markaya eklenen belgeler paylaşılır. Dosyayı açıp içindeki bilgilerin markayla paylaşılabileceğini kontrol edin; dosya adı ve içeriği müşteriye görünür, iç açıklama notu görünmez.</p>{documents.isPending&&<LoadingState label="Belgeler yükleniyor…" />}{documents.data?.map(d=>{const shared=shares.data?.find(s=>s.documentId===d.id&&!s.revokedAt);return <div className="flex flex-wrap items-center gap-3 rounded-lg border p-3 text-sm" key={d.id}><span className="min-w-0 break-all">{d.fileName}</span><button disabled={busy||shares.isPending||shares.isError} className={button} onClick={async()=>{if(!(await confirm({title:shared?'Paylaşımı kapat':'Belgeyi paylaş',message:shared?'Bu belgenin portal erişimi kapatılsın mı? İndirilen kopyalar silinemez.':'Bu dosyanın içeriğini kontrol ettiniz mi? Bu markanın tüm etkin müşteri hesapları dosyayı indirebilecek.',tone:'danger',confirmLabel:shared?'Kapat':'Paylaş'})))return;void act(shared?`/documents/${shared.id}/revoke`:'/documents',shared?undefined:{documentId:d.id});}}>{shared?'Belge paylaşımını kapat':'Belgeyi paylaş'}</button></div>})}{!documents.isPending&&!documents.data?.length&&<EmptyState message="Önce yukarıdaki alandan markaya belge ekleyin." />}</Card>
    <PortalReportFollowup brandId={brandId}/>
    <PortalConversations brandId={brandId}/>
    <PortalRequests brandId={brandId}/>
    <PortalSubmissionList brandId={brandId}/>
  </div>;
}
function AccountForm({account,busy,onSubmit}:{account?:Account;busy:boolean;onSubmit:(e:FormEvent<HTMLFormElement>)=>void}){return <form className="mt-3 grid gap-3 sm:grid-cols-2" onSubmit={onSubmit}><label className="text-sm">Ad soyad<input required name="name" maxLength={160} defaultValue={account?.name} className="input mt-1" disabled={busy}/></label><label className="text-sm">E-posta<input required name="email" type="email" maxLength={320} defaultValue={account?.email} className="input mt-1" disabled={busy}/></label><label className="text-sm">{account?'Yeni şifre (değişmeyecekse boş bırakın)':'İlk giriş şifresi'}<input required={!account} name="password" type="password" minLength={10} maxLength={256} autoComplete="new-password" className="input mt-1" disabled={busy}/></label><label className="flex items-center gap-2 text-sm"><input name="active" type="checkbox" defaultChecked={account?.isActive??true} disabled={busy}/>Portal erişimi açık</label><button className={button} disabled={busy}>{account?'Hesabı güncelle':'Müşteri hesabını oluştur'}</button></form>;}
