'use client';
import { FormEvent, useState } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { api } from '@/lib/api';
import { notify } from '@/components/feedback';
import { Badge, Card, PageHeader } from '@/components/ui/core';
type User={id:string;email:string;name:string;role:string;isActive:boolean;createdAt:string};
const initial={email:'',name:'',role:'Analyst',password:'',isActive:true};
export default function Page(){const qc=useQueryClient();const{data=[]}=useQuery({queryKey:['users'],queryFn:()=>api<User[]>('/api/users')});const[f,setF]=useState(initial);function c(k:string,v:string|boolean){setF(x=>({...x,[k]:v}))}async function submit(e:FormEvent){e.preventDefault();await api('/api/users',{method:'POST',body:JSON.stringify(f)});notify('Kullanıcı oluşturuldu.');setF(initial);await qc.invalidateQueries({queryKey:['users']})}return <><PageHeader title="Kullanıcılar" description="OVO Growth OS erişimlerini ve rollerini yönetin."/><div className="grid gap-4 xl:grid-cols-[1fr_380px]"><div className="space-y-3">{data.map(u=><Card key={u.id} className="flex items-center justify-between gap-3 p-5"><div><h2 className="font-semibold">{u.name}</h2><p className="text-sm text-[#6d7175]">{u.email}</p></div><div className="text-right"><Badge tone={u.isActive?'green':'neutral'}>{u.isActive?'Etkin':'Pasif'}</Badge><div className="mt-1 text-xs text-[#6d7175]">{u.role}</div></div></Card>)}</div><Card className="h-fit p-5"><h2 className="font-semibold">Yeni kullanıcı</h2><form onSubmit={submit} className="mt-4 space-y-3">{[['name','Ad soyad'],['email','E-posta'],['password','Geçici şifre']].map(([k,l])=><label key={k}><span className="label">{l}</span><input className="input mt-1.5" type={k==='password'?'password':'text'} required value={String(f[k as keyof typeof f])} onChange={e=>c(k,e.target.value)}/></label>)}<label><span className="label">Rol</span><select className="input mt-1.5" value={f.role} onChange={e=>c('role',e.target.value)}><option>Analyst</option><option>Partner</option><option>Admin</option></select></label><button className="w-full rounded-lg bg-[#303030] px-4 py-2 text-sm font-semibold text-white">Kullanıcı oluştur</button></form></Card></div></>}
