'use client';
import Link from 'next/link';
import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { api, moneyPrecise } from '@/lib/api';
import { Badge, Card, PageHeader } from '@/components/ui/core';
import { dayText } from '@/components/work-tasks';
import type { CollectionBalance } from '@/components/collection-panel';
import { promiseState, type PromiseBalance } from '@/components/collection-promise-panel';

const ageLabels: Record<string, string> = { Unknown: 'Vadesi bilinmiyor', NotDue: 'Vadesi bugün veya ileride', Days1To30: '1–30 gün gecikmiş', Days31To60: '31–60 gün gecikmiş', Days61To90: '61–90 gün gecikmiş', Over90: '90 günden fazla gecikmiş' };
type Row = { id: string; brandId: string; brandName: string; year: number; month: number; invoiceReference: string; dueOn: string | null; balance: CollectionBalance; age: string; promise: PromiseBalance | null };
type Week = { from: string; through: string; amount: number; count: number };
type Plan = { today: string; currency: string; weeks: number; closedPeriods: number; outstanding: number; overdue: number; unknownDue: number; afterHorizon: number; legacyPaid: number;
  aging: { age: string; count: number; amount: number }[]; upcoming: Week[]; received: Week[]; items: Row[]; reviewItems: Row[]; promised: Week[]; overduePromises: number; afterHorizonPromises: number; unpromised: number };

export default function CollectionPlanningPage() {
  const [weeks, setWeeks] = useState(4); const [currency, setCurrency] = useState(''); const [age, setAge] = useState('');
  const [promiseView, setPromiseView] = useState(false);
  const query = useQuery({ queryKey: ['collection-planning', weeks, currency], queryFn: () => api<{ currencies: string[]; plan: Plan }>(`/api/collection-planning?weeks=${weeks}${currency ? `&currency=${currency}` : ''}`) });
  const plan = query.data?.plan; const amount = (value: number) => moneyPrecise(value, plan?.currency ?? 'TRY');
  const items = plan?.items.filter(x => !age || x.age === age) ?? [];
  return <><PageHeader title="Alacak yaşı ve vade takvimi" description="Kalan alacağı ve kayıtlı vadelere göre beklenen girişi inceleyin. Vade bir ödeme sözü veya tahsilat garantisi değildir." />
    <div className="mb-4 flex flex-wrap gap-4 text-sm"><Link href="/commissions" className="underline">Hakedişlere dön</Link><Link href="/guide#alacak-yasi-ve-vade-takvimi" className="underline">Nasıl kullanılır?</Link></div>
    <Card className="mb-4 p-5"><div className="flex flex-wrap items-end gap-3"><label>Takvim uzunluğu<select className="input mt-1" value={weeks} onChange={e => setWeeks(Number(e.target.value))}>{[4, 8, 12].map(n => <option value={n} key={n}>{n} hafta</option>)}</select></label>
      <label>Para birimi<select className="input mt-1" value={currency || plan?.currency || ''} onChange={e => setCurrency(e.target.value)}><option value="" disabled>Para birimi seçin</option>{query.data?.currencies.map(x => <option key={x}>{x}</option>)}</select></label>
      <button className="rounded-lg border px-3 py-2 text-sm disabled:opacity-50" disabled={query.isFetching} onClick={() => query.refetch()}>Takvimi yenile</button></div>
      <p className="mt-3 text-sm">Hakediş listesindeki ay ve marka filtrelerinden bağımsız olarak bütün kilitli, faturalanmış veya ödenmiş aylar incelenir. Taslak ve yalnız onaylı kayıtlar alınmaz. Para birimleri birbirine eklenmez. Tutarlar KDV hariçtir; şirketin banka bakiyesi veya tüm para giriş/çıkış planı değildir.</p></Card>
    {query.isPending ? <p role="status">Tahsilat takvimi yükleniyor…</p> : query.isError ? <p role="alert">{query.error.message}</p> : plan && <>
      <p className="mb-4 text-sm">Hesap tarihi: {dayText(plan.today)} (Türkiye) · {plan.closedPeriods} kapanmış dönem. Takvimler birbirinden farklı tarih aralıklarını gösterir.</p>
      {plan.closedPeriods === 0 ? <Card className="p-5">Bu para biriminde kapanmış dönem kaydı yok. Bu, işletmenin hiç alacağı olmadığı anlamına gelmez.</Card> : <>
        <div className="mb-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[['Toplam kalan alacak', plan.outstanding], ['Vadesi geçmiş kalan', plan.overdue], ['Vadesi bilinmeyen kalan', plan.unknownDue], ['Seçili takvimden sonraki vadeler', plan.afterHorizon]].map(([label, value]) => <Card key={String(label)} className="p-4"><p className="text-sm">{label}</p><p className="mt-2 break-words text-lg font-semibold">{amount(Number(value))}</p></Card>)}</div>
        <Card className="mb-4 p-5"><h2 className="font-semibold">Kalan alacak kaç gündür bekliyor?</h2><p className="my-3 text-sm">Her kalan alacak yalnız bir grupta yer alır. Bugün vadeli iş henüz gecikmiş değildir. Vadesi bilinmeyene gecikme günü uydurulmaz.</p><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{plan.aging.map(x => <div className="rounded-lg border p-3" key={x.age}><p>{ageLabels[x.age]}</p><strong className="block break-words">{amount(x.amount)}</strong><p className="text-sm">{x.count} dönem</p></div>)}</div></Card>
        <Card className="mb-4 p-5"><label>Beklenti takviminin kaynağı<select className="input mt-1 max-w-sm" value={promiseView ? 'promise' : 'due'} onChange={e => setPromiseView(e.target.value === 'promise')}><option value="due">Kayıtlı vadeler</option><option value="promise">Bildirilen ödeme sözleri</option></select></label><p className="mt-3 text-sm">Aynı alacağın iki ayrı görünümüdür; vade ile söz tutarlarını toplamayın. Üstteki yaş grupları her zaman gerçek vadeye göre kalır. Ödeme sözü bulunmayan tutara tarih veya garanti uydurulmaz.</p>
          {promiseView && <dl className="mt-3 grid gap-3 sm:grid-cols-3">{[['Tarihi geçmiş sözlerden kalan', plan.overduePromises], ['Takvim sonrasındaki sözlerden kalan', plan.afterHorizonPromises], ['Güncel sözle karşılanmayan alacak', plan.unpromised]].map(([label, value]) => <div className="rounded-lg border p-3" key={String(label)}><dt className="text-sm">{label}</dt><dd className="mt-1 break-words font-semibold">{amount(Number(value))}</dd></div>)}</dl>}
        </Card>
        <div className="mb-4 grid items-start gap-4 xl:grid-cols-2"><Card className="min-w-0 p-5"><h2 className="font-semibold">Önümüzdeki {weeks} hafta: {promiseView ? 'ödeme sözlerinden beklenen' : 'vadelere göre beklenen'}</h2><p className="my-3 text-sm">{promiseView ? 'Yalnız kaynağı kayıtlı güncel sözün, son söz kaydından sonraki geçerli ödemeler düşülmüş kalan kısmı gösterilir. Kaldırılmış sözler dahil edilmez; tarihi geçmiş sözler bugüne taşınmaz. Sıfır, o hafta için kayıtlı söz olmaması anlamına da gelebilir.' : 'Bugünden başlayarak yedi günlük dilimler. Gecikmiş alacaklar bugüne taşınmaz; bilinmeyen vadeler ve takvim dışındakiler üstte ayrıdır. Sıfır, bu dilime denk gelen kayıtlı vade olmadığı anlamına da gelebilir.'}</p><WeekList rows={promiseView ? plan.promised : plan.upcoming} currency={plan.currency} unit="dönem" /></Card>
        <Card className="min-w-0 p-5"><h2 className="font-semibold">Son {weeks} hafta: gerçekleşmiş ödemeler</h2><p className="my-3 text-sm">Bugün dahil geriye doğru aynı uzunlukta dönem. Gerçek ödeme tarihi esas alınır; hakedişin ait olduğu ay farklı olabilir. İptal edilen ödemeler hariçtir.</p><WeekList rows={plan.received} currency={plan.currency} unit="ödeme" /><p className="mt-3 text-sm">Bu takvime eklenmeyen, ödeme tarihi bilinmeyen eski ödenmiş tutar (tüm aylar): <strong>{amount(plan.legacyPaid)}</strong>. Bu tutara tarih uydurulmaz.</p></Card></div>
        <Card className="mb-4 p-5"><h2 className="font-semibold">Alacağı kalan dönemler</h2><label className="my-3 block max-w-sm">Gecikme grubuna göre listele<select className="input mt-1" value={age} onChange={e => setAge(e.target.value)}><option value="">Bütün kalan alacaklar</option>{Object.entries(ageLabels).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label><p className="mb-3 text-sm">Bu seçim yalnız aşağıdaki listeyi süzer; üstteki toplamları ve takvimleri değiştirmez. Ödeme veya vade girmek için ilgili dönemi açın.</p>
          <div className="space-y-3">{items.map(x => <article key={x.id} className="rounded-lg border p-4"><div className="flex flex-wrap items-start justify-between gap-2"><Link className="font-semibold underline" href={`/commissions/${x.id}`}>{x.brandName} · {x.month}/{x.year}</Link><Badge tone={x.balance.overdueDays > 0 ? 'red' : 'neutral'}>{ageLabels[x.age]}</Badge></div><p className="mt-2 break-words">Kalan: <strong>{amount(x.balance.outstanding)}</strong> · Ödenen: {amount(x.balance.paid)}</p><p className="mt-2 break-words text-sm">Vade: {dayText(x.dueOn)}{x.balance.overdueDays > 0 && ` · ${x.balance.overdueDays} gün gecikti`} · Fatura: {x.invoiceReference || 'Kayıtlı değil'}</p><p className="mt-2 text-sm">{x.promise ? `${promiseState(x.promise.state)} · ${dayText(x.promise.promisedOn)} · Sözden kalan: ${amount(x.promise.remaining)}` : 'Kayıtlı ödeme sözü yok.'} <Link className="underline" href={`/commissions/${x.id}#payment-promise`}>Sözü ve takibi aç</Link></p></article>)}</div>{items.length === 0 && <p>Bu grupta kalan alacak kaydı yok.</p>}</Card>
      </>}
      {plan.reviewItems.length > 0 && <Card className="mb-4 border-amber-400 p-5"><h2 className="font-semibold">Toplamlara alınmayan, inceleme gereken kayıtlar</h2><p className="my-3 text-sm">Negatif hakediş veya hakedişi aşan ödeme nedeniyle aşağıdaki dönemler vade/ödeme takvimlerinden ve üstteki tutarlardan çıkarıldı. Bu nedenle toplamlar eksik olabilir; yöneticinizle kayıtları kontrol edin.</p><ul className="space-y-2">{plan.reviewItems.map(x => <li key={x.id}><Link className="underline" href={`/commissions/${x.id}`}>{x.brandName} · {x.month}/{x.year}</Link> · Kayıtlı hakediş: {amount(x.balance.receivable)} · Ödenen: {amount(x.balance.paid)}</li>)}</ul></Card>}
    </>}
  </>;
}

function WeekList({ rows, currency, unit }: { rows: Week[]; currency: string; unit: string }) {
  return <ul className="space-y-3">{rows.map(x => <li key={x.from} className="rounded-lg border p-3"><p className="text-sm">{dayText(x.from)} – {dayText(x.through)}</p><p className="mt-1 break-words font-semibold">{moneyPrecise(x.amount, currency)}</p><p className="text-sm">{x.count} {unit}</p></li>)}</ul>;
}
