"use client";
import {BrandTeam} from "@/components/brand-team";
import {BrandApiSettingsCard} from "@/components/brand-api-settings";
import {StoreOrdersCard} from "@/components/store-orders";
import {BrandHealthCard} from "@/components/brand-health";
import {AdEfficiencyCard} from "@/components/ad-efficiency";
import {MeetingBrief} from "@/components/meeting-brief";
import {BrandSatisfaction} from "@/components/brand-satisfaction";
import {BrandAdSettingsCard} from "@/components/brand-ad-settings";
import {SalesChannelsCard} from "@/components/sales-channels";
import {PortfolioReportView} from "@/components/portfolio-report";
import Link from"next/link";import{FormEvent,useEffect,useRef,useState}from"react";import{useParams}from"next/navigation";import{useQuery,useQueryClient}from"@tanstack/react-query";import{api,money,percent}from"@/lib/api";import{notify}from"@/components/feedback";import{Badge,Card,EmptyState,ErrorState,LoadingState,MetricCard,PageHeader,PrimaryLink}from"@/components/ui/core";import{useDialog}from"@/components/ui/modal";import{turkce}from"@/lib/turkish";import{brandTabs,resolveBrandTab,type BrandTabId}from"@/lib/brand-tabs";import{FieldHint}from"@/components/field-hint";
const fieldHints:Record<string,string>={name:"Markanın müşterilerin bildiği kısa adı. Listelerde ve raporlarda böyle görünür.",legalName:"Fatura ve sözleşmelerde geçen resmî şirket unvanı.",website:"Markanın satış yaptığı internet adresi.",industry:"Markanın faaliyet gösterdiği ana sektör (ör. giyim, kozmetik).",subIndustry:"Sektörün alt kırılımı (ör. kadın giyim). Raporlarda gruplamaya yarar.",contactName:"Marka tarafında görüştüğümüz kişinin adı.",contactEmail:"Yetkiliyle iletişim için kullanılacak e-posta adresi.",contactPhone:"Yetkiliyle iletişim için telefon numarası.",country:"Markanın faaliyet gösterdiği ülkenin iki harfli kodu.",currency:"Hesapların tutulduğu para birimi. Sonradan değiştirmeyin.",businessModel:"Markanın nasıl satış yaptığı: kendi sitesi, pazaryeri, perakende veya karışık.",platform:"Markanın mağazasının çalıştığı teknik altyapı. Sipariş ve veri bağlantılarını etkiler.",status:"Markanın şu anki aşaması (aday, değerlendirme, aktif vb.)."};
type Brand={id:string;name:string;legalName:string;website:string;industry:string;subIndustry:string;platform:string;businessModel:string;country:string;currency:string;status:string;contactName:string;contactEmail:string;contactPhone:string;economics?:{averageMonthlyRevenue:number;grossMarginRate:number;currentAdSpend:number;returnRate:number;stockCoverageDays:number};evaluations:{id:string;status:string;partnershipScore:number;dataConfidenceScore:number;decision:string;recommendedDealType:string;recommendedMinimumFee:number;updatedAt:string}[];deals:{id:string;name:string;status:string;dealType:string}[]};
export default function BrandDetail(){const{id}=useParams<{id:string}>();const qc=useQueryClient();const[editing,setEditing]=useState(false);const[tab,setTab]=useState<BrandTabId>("ozet");const[anchor,setAnchor]=useState<string|null>(null);const tabButtons=useRef<(HTMLButtonElement|null)[]>([]);const{data:b,isLoading,error}=useQuery({queryKey:["brand",id],queryFn:()=>api<Brand>(`/api/brands/${id}`)});const{confirm}=useDialog();
useEffect(()=>{const resolve=()=>{const{tab:next,anchor:target}=resolveBrandTab(window.location.hash,new URLSearchParams(window.location.search).get("bolum"));setTab(next);setAnchor(target)};resolve();window.addEventListener("hashchange",resolve);window.addEventListener("popstate",resolve);return()=>{window.removeEventListener("hashchange",resolve);window.removeEventListener("popstate",resolve)}},[]);
useEffect(()=>{if(!anchor)return;const frame=requestAnimationFrame(()=>document.getElementById(anchor)?.scrollIntoView({block:"start"}));return()=>cancelAnimationFrame(frame)},[tab,anchor]);
if(isLoading)return <Card><LoadingState /></Card>;if(error||!b)return <Card><ErrorState message={error?.message??"Marka bulunamadı"} /></Card>;const latest=[...b.evaluations].sort((a,c)=>c.updatedAt.localeCompare(a.updatedAt))[0];
function selectTab(next:BrandTabId){setTab(next);setAnchor(null);const url=new URL(window.location.href);url.searchParams.set("bolum",next);url.hash="";window.history.replaceState(null,"",url)}
function tabKey(event:React.KeyboardEvent,index:number){let target=index;if(event.key==="ArrowRight")target=(index+1)%brandTabs.length;else if(event.key==="ArrowLeft")target=(index-1+brandTabs.length)%brandTabs.length;else if(event.key==="Home")target=0;else if(event.key==="End")target=brandTabs.length-1;else return;event.preventDefault();selectTab(brandTabs[target].id);tabButtons.current[target]?.focus()}
async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const value=(name:string)=>String(f.get(name)??"");await api(`/api/brands/${id}`,{method:"PUT",body:JSON.stringify({name:value("name"),legalName:value("legalName"),website:value("website"),country:value("country"),currency:value("currency"),industry:value("industry"),subIndustry:value("subIndustry"),businessModel:value("businessModel"),platform:value("platform"),status:value("status"),contactName:value("contactName"),contactEmail:value("contactEmail"),contactPhone:value("contactPhone")})});notify("Marka bilgileri kaydedildi.");setEditing(false);await qc.invalidateQueries({queryKey:["brand",id]});await qc.invalidateQueries({queryKey:["brands"]})}
async function archive(){if(!(await confirm({title:"Markayı arşivle",message:"Bu markayı arşivlemek istediğinize emin misiniz? Etkin anlaşması olan markalar arşivlenemez.",tone:"danger",confirmLabel:"Arşivle"})))return;await api(`/api/brands/${id}/archive`,{method:"POST"});notify("Marka arşivlendi.");await qc.invalidateQueries({queryKey:["brand",id]})}
return <><PageHeader title={b.name} description={`${b.industry||"Sektör belirtilmedi"} · ${turkce(b.platform)} · ${b.country}`} action={<div className="flex flex-wrap gap-2"><button onClick={()=>setEditing(x=>!x)} className="rounded-lg border bg-white px-3.5 py-2 text-sm font-semibold">{editing?"Düzenlemeyi kapat":"Bilgileri düzenle"}</button><PrimaryLink href={`/evaluations/new?brandId=${b.id}`}>Yeni değerlendirme</PrimaryLink></div>}/>
{editing&&<Card className="mb-4 p-5"><h2 className="font-semibold">Marka ve iletişim bilgileri</h2><form onSubmit={save} className="mt-4 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{[["name","Marka adı"],["legalName","Resmî unvan"],["website","İnternet sitesi"],["industry","Sektör"],["subIndustry","Alt sektör"],["contactName","İletişim kişisi"],["contactEmail","E-posta"],["contactPhone","Telefon"],["country","Ülke kodu"],["currency","Para birimi"]].map(([name,label])=><label key={name}><span className="label">{label}{fieldHints[name]&&<FieldHint text={fieldHints[name]}/>}</span><input className="input mt-1.5" name={name} type={name==="contactEmail"?"email":"text"} defaultValue={String(b[name as keyof Brand]??"")}/></label>)}<Select name="businessModel" label="İş modeli" value={b.businessModel} options={["Dtc","Retail","Marketplace","Hybrid"]}/><Select name="platform" label="E-ticaret altyapısı" value={b.platform} options={["Shopify","GrandNode","Custom","Other"]}/><Select name="status" label="Marka durumu" value={b.status} options={["Lead","Evaluation","Negotiation","Active","Paused","Rejected","Closed"]}/><div className="md:col-span-2 xl:col-span-3 flex justify-between border-t pt-4"><button type="button" onClick={archive} className="rounded-lg border border-[#f1aaa4] px-4 py-2 text-sm font-semibold text-[#8e1f0b]">Markayı arşivle</button><button className="rounded-lg bg-[#303030] px-4 py-2 text-sm font-semibold text-white">Değişiklikleri kaydet</button></div></form></Card>}
<div className="sticky top-16 z-20 -mx-4 border-b border-[#dfe3e8] bg-[#f4f5f5] px-4 sm:-mx-6 sm:px-6">
  <div role="tablist" aria-label="Marka bölümleri" className="flex gap-1.5 overflow-x-auto py-2">{brandTabs.map((t,i)=><button key={t.id} ref={el=>{tabButtons.current[i]=el}} type="button" role="tab" id={`sekme-${t.id}`} aria-controls={`bolum-${t.id}`} aria-selected={tab===t.id} tabIndex={tab===t.id?0:-1} onClick={()=>selectTab(t.id)} onKeyDown={e=>tabKey(e,i)} className={`shrink-0 rounded-lg border px-3 py-2 text-sm ${tab===t.id?"border-[#dfe3e8] bg-white font-semibold shadow-sm":"border-transparent text-[#4a4d50] hover:bg-white"}`}>{t.label}</button>)}</div>
</div>
<div role="tabpanel" id="bolum-ozet" aria-labelledby="sekme-ozet" hidden={tab!=="ozet"} className="pt-4">
  <p className="mb-3 text-sm text-[#6d7175]">Aşağıdaki bilgiler marka değerlendirmesinden gelir; belirli bir ayın gerçekleşen sonucu değildir. Gerçekleşen sonuçlar ve hakedişler <strong>Performans</strong> sekmesinde ayrıca gösterilir.</p>
  <div className="grid grid-cols-2 gap-3 xl:grid-cols-4"><MetricCard label="DEĞERLENDİRME CİROSU" value={b.economics?money(b.economics.averageMonthlyRevenue,b.currency):"Bilgi yok"}/><MetricCard label="BRÜT KÂR MARJI" value={b.economics?percent(b.economics.grossMarginRate):"Bilgi yok"} tone={(b.economics?.grossMarginRate??0)<.3?"red":"green"}/><MetricCard label="DEĞERLENDİRME REKLAM GİDERİ" value={b.economics?money(b.economics.currentAdSpend,b.currency):"Bilgi yok"}/><MetricCard label="İŞ ORTAKLIĞI PUANI" value={latest?`${latest.partnershipScore} / 100`:"Bilgi yok"} tone={(latest?.partnershipScore??0)<55?"red":"green"}/></div>
  <div className="mt-4 grid gap-4 xl:grid-cols-[1.5fr_1fr]"><Card className="p-5"><div className="flex items-center justify-between"><h2 className="font-semibold">Son değerlendirme</h2>{latest&&<Badge tone={latest.decision==="Accept"?"green":latest.decision==="Reject"?"red":"yellow"}>{turkce(latest.decision)}</Badge>}</div>{latest?<><div className="mt-5 grid grid-cols-2 gap-4"><Info l="Durum" v={turkce(latest.status)}/><Info l="Veri güven puanı" v={`${latest.dataConfidenceScore} / 100`}/><Info l="Önerilen anlaşma" v={turkce(latest.recommendedDealType)}/><Info l="Asgari aylık ücret" v={money(latest.recommendedMinimumFee,b.currency)}/></div><div className="mt-5 flex flex-wrap gap-2"><Link className="rounded-lg border px-3 py-2 text-sm font-semibold" href={`/evaluations/${latest.id}`}>Değerlendirmeyi aç</Link><Link className="rounded-lg border px-3 py-2 text-sm font-semibold" href={`/evaluations/${latest.id}/scenarios`}>Senaryolar</Link><Link className="rounded-lg border px-3 py-2 text-sm font-semibold" href={`/evaluations/${latest.id}/deals`}>Anlaşma seçenekleri</Link></div></>:<EmptyState message="Henüz değerlendirme yapılmadı." />}</Card><Card className="p-5"><h2 className="font-semibold">Mevcut anlaşma</h2>{b.deals.length?<div className="mt-4"><div className="font-semibold">{b.deals[0].name}</div><div className="mt-2 flex gap-2"><Badge tone={b.deals[0].status==="Active"?"green":"blue"}>{turkce(b.deals[0].status)}</Badge><Badge>{turkce(b.deals[0].dealType)}</Badge></div></div>:<EmptyState message="Henüz anlaşma oluşturulmadı." />}<div className="mt-5 border-t pt-4 text-sm"><span className="text-[#6d7175]">Marka durumu</span><span className="float-right font-semibold">{turkce(b.status)}</span></div></Card></div>
</div>
<div role="tabpanel" id="bolum-gorusme" aria-labelledby="sekme-gorusme" hidden={tab!=="gorusme"} className="pt-4">
  <MeetingBrief brandId={b.id}/><BrandSatisfaction brandId={b.id}/><BrandTeam brandId={id}/>
</div>
<div role="tabpanel" id="bolum-performans" aria-labelledby="sekme-performans" hidden={tab!=="performans"} className="pt-4">
  <Card className="mt-4 p-5"><h2 className="font-semibold">Aylık hedef ve bütçe</h2><p className="mt-2 text-sm">Net ciro hedefini, reklam bütçesini ve katkı marjını gerçekleşen sonuçla karşılaştırın.</p><Link className="mt-3 inline-block underline" href={`/brands/${id}/targets`}>Hedefleri ve takip işlerini aç</Link></Card>
  <BrandHealthCard brandId={b.id}/><AdEfficiencyCard brandId={b.id} currency={b.currency}/><PortfolioReportView title="Gerçekleşen aylık sonuçlar" brandId={b.id} showCharts/>
</div>
<div role="tabpanel" id="bolum-baglantilar" aria-labelledby="sekme-baglantilar" hidden={tab!=="baglantilar"} className="pt-4">
  <SalesChannelsCard brandId={b.id}/><BrandAdSettingsCard brandId={b.id}/><BrandApiSettingsCard brandId={b.id}/><StoreOrdersCard brandId={b.id}/>
</div>
</>}
function Select({name,label,value,options}:{name:string;label:string;value:string;options:string[]}){return <label><span className="label">{label}{fieldHints[name]&&<FieldHint text={fieldHints[name]}/>}</span><select className="input mt-1.5" name={name} defaultValue={value}>{options.map(x=><option key={x} value={x}>{turkce(x)}</option>)}</select></label>}function Info({l,v}:{l:string;v:string}){return <div><div className="label">{l}</div><div className="mt-1 text-sm font-semibold">{v}</div></div>}
