const labels: Record<string, string> = {
  Active: "Aktif",
  Accepted: "Kabul edildi",
  Analyzed: "Analiz edildi",
  Approved: "Onaylandı",
  Archived: "Arşivlendi",
  Calculated: "Hesaplandı",
  Draft: "Taslak",
  Evaluation: "Değerlendirme",
  InProgress: "Devam ediyor",
  InternalReview: "İç değerlendirmede",
  Invoiced: "Faturalandı",
  Lead: "Potansiyel marka",
  Locked: "Kilitlendi",
  Negotiation: "Görüşmede",
  Paid: "Ödendi",
  Proposed: "Teklif edildi",
  ReadyForAnalysis: "Analize hazır",
  Rejected: "Reddedildi",
  UnderReview: "İncelemede",
  Accept: "Kabul et",
  ConditionalAccept: "Koşullu kabul",
  NeedMoreData: "Ek bilgi gerekli",
  Reject: "Reddet",
  Healthy: "İyi",
  Watch: "İzlenmeli",
  "At Risk": "Riskli",
  High: "Yüksek",
  Critical: "Kritik",
  Medium: "Orta",
  Low: "Düşük",
  Normal: "Normal",
  Info: "Bilgi",
  Warning: "Uyarı",
  Verified: "Doğrulandı",
  ProvidedByBrand: "Marka beyanı",
  Estimated: "Tahmini",
  Unknown: "Bilinmiyor",
  Dtc: "Doğrudan tüketiciye satış",
  Custom: "Özel yazılım",
  Other: "Diğer",
  FlatRevenueShare: "Sabit ciro payı",
  TieredRevenueShare: "Kademeli ciro payı",
  RetainerPlusRevenueShare: "Aylık hizmet bedeli + ciro payı",
  MinimumFeePlusRevenueShare: "Asgari ücret + ciro payı",
  IncrementalRevenueShare: "Büyüme farkı üzerinden pay",
  RetainerPlusIncrementalRevenueShare: "Aylık hizmet bedeli + büyüme farkı payı",
  ContributionProfitShare: "Katkı kârı paylaşımı",
  FixedRetainer: "Sabit aylık hizmet bedeli",
  Manual: "Elle girilen",
  Financial: "Finansal",
  Risk: "Risk",
  Recommendation: "Öneri",
  GrossMargin: "Brüt kâr marjı",
  ReturnRate: "İade oranı",
  StockCoverageDays: "Stok yeterlilik günü",
  FounderCooperation: "Kurucu iş birliği",
  OperationalReadiness: "Operasyonel hazırlık",
  ProductMarketFit: "Ürün-pazar uyumu",
  CurrentAdSpend: "Mevcut reklam harcaması",
  AverageMonthlyRevenue: "Ortalama aylık ciro",
  PartnershipScore: "İş ortaklığı puanı",
  Equal: "Eşittir",
  NotEqual: "Eşit değildir",
  GreaterThan: "Büyüktür",
  GreaterThanOrEqual: "Büyük veya eşittir",
  LessThan: "Küçüktür",
  LessThanOrEqual: "Küçük veya eşittir",
  Between: "Arasındadır",
  None: "Etkisi yok",
  PureRevenueShareNotAllowed: "Yalnızca ciro payına izin verme",
  PreferRetainerLowShare: "Aylık ücret ve düşük payı tercih et",
  AllowTieredHybrid: "Kademeli karma modele izin ver",
  AllowFourToSixPercent: "%4–6 paya izin ver",
  AllowFiveToEightPercent: "%5–8 paya izin ver",
  BrandCreated: "Marka oluşturuldu",
  EvaluationCreated: "Değerlendirme oluşturuldu",
  EvaluationSaved: "Değerlendirme kaydedildi",
  EvaluationAnalyzed: "Değerlendirme analiz edildi",
  EvaluationApproved: "Değerlendirme onaylandı",
  RuleSetCloned: "Kural seti kopyalandı",
  RuleChanged: "Kural değiştirildi",
  RuleSetPublished: "Kural seti yayımlandı",
  RuleSetArchived: "Kural seti arşivlendi",
  DealCreated: "Anlaşma oluşturuldu",
  DealChanged: "Anlaşma değiştirildi",
  DealActivated: "Anlaşma etkinleştirildi",
  MonthlyPerformanceCreated: "Aylık sonuç oluşturuldu",
  MonthlyPerformanceChanged: "Aylık sonuç değiştirildi",
  MonthlyPerformanceSubmitted: "Aylık sonuç incelemeye gönderildi",
  MonthlyPerformanceApproved: "Aylık sonuç onaylandı",
  MonthlyCloseLocked: "Aylık dönem kilitlendi",
  MonthlyCloseUnlocked: "Aylık dönem kilidi açıldı",
  CommissionAdjusted: "Hakediş düzeltildi",
  CommissionInvoiced: "Hakediş faturalandı",
  CommissionPaid: "Hakediş ödendi",
  SettingsChanged: "Ayarlar değiştirildi",
  Brand: "Marka",
  RuleSet: "Kural seti",
  Rule: "Kural",
  Deal: "Anlaşma",
  MonthlyPerformance: "Aylık sonuç",
  Settings: "Ayarlar",
  "Gross margin below 25%": "Brüt kâr marjı %25'in altında",
  "Gross margin below 30%": "Brüt kâr marjı %30'un altında",
  "Gross margin 30%-40%": "Brüt kâr marjı %30-%40 arasında",
  "Gross margin 40%-50%": "Brüt kâr marjı %40-%50 arasında",
  "Gross margin 50%-60%": "Brüt kâr marjı %50-%60 arasında",
  "Gross margin at least 60%": "Brüt kâr marjı en az %60",
  "Return rate above 25%": "İade oranı %25'in üzerinde",
  "Stock coverage below 30 days": "Stok yeterliliği 30 günün altında",
  "Stock coverage 30-60 days": "Stok yeterliliği 30-60 gün arasında",
  "Founder cooperation is weak": "Kurucu iş birliği zayıf",
  "Operational readiness is weak": "Operasyonel hazırlık zayıf",
  "Product-market fit is weak": "Ürün-pazar uyumu zayıf",
  "Healthy gross margin supports performance pricing.": "Sağlıklı brüt kâr marjı performansa dayalı fiyatlamayı destekliyor.",
  "Strong product-market fit.": "Ürün-pazar uyumu güçlü.",
  "Stock coverage supports growth.": "Stok yeterliliği büyümeyi destekliyor.",
  "Minimum monthly media budget": "Asgari aylık medya bütçesi",
  "Analytics access": "Analiz araçlarına erişim",
  "Commerce admin access": "E-ticaret yönetim erişimi",
  "Meta Business access": "Meta Business erişimi",
  "Google Ads access": "Google Ads erişimi",
  "Merchant Center access": "Merchant Center erişimi",
  "Monthly financial reporting": "Aylık finansal raporlama",
  "Minimum 60 days stock": "En az 60 günlük stok",
  "Margin verification": "Marj doğrulaması",
  "Weekly creative commitment": "Haftalık içerik üretimi",
};

export function turkce(value: string | null | undefined) {
  if (!value) return "—";
  return labels[value] ?? value;
}

export function turkceTarih(value: string) {
  return new Intl.DateTimeFormat("tr-TR", { dateStyle: "short", timeStyle: "short" }).format(new Date(value));
}
